[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"

[logging]
filename="logs/burrow.log"
level="info"
maxsize=10
maxbackups=3
use-compression=true

[zookeeper]
servers=["localhost:12181","localhost:22181","localhost:32181"]

[cluster.fastcampus]
class-name="kafka"
servers=["localhost:19092","localhost:29092","localhost:39092"]
topic-refresh=60
offset-refresh=10

[consumer.fastcampus]
class-name="kafka"
cluster="fastcampus"
servers=["localhost:19092","localhost:29092","localhost:39092"]
group-denylist=""
group-allowlist=""

[httpserver.listener]
address=":8000"
timeout=300

[storage.inmemory]
class-name="inmemory"
min-distance=1
workers=20
intervals=10
expire-group=604800
